### ISSUE TITLE
Logging page is blank (some logs in file, errors in browser)

### ISSUE THREAD

**Issue by remz1337** [nextcloud/logreader#1093]
### Steps to reproduce
1. Migrate from NC 27 to NC 28 (in fact maybe the issue was present in NC27, but didn't use the log viewer then)
2. Go to Logging page

### Expected behaviour
See the logs that are in the `nextcloud.log` file

### Actual behaviour
Logging page is empty (website still works, just the content area isn't displaying anything).

## Server configuration detail

**Operating system:** Linux 5.15.126-1-pve #1 SMP PVE 5.15.126-1 (2023-10-03T17:24Z) x86_64

**Webserver:** nginx/1.18.0 (fpm-fcgi)

**Database:** pgsql PostgreSQL 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit

**PHP version:** 8.1.2-1ubuntu2.14

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, cgi-fcgi, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, exif, pdo_pgsql, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 28.0.1 - 28.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from last stable (27.X)

**Where did you install Nextcloud from:** manual install

<details><summary>Signing status</summary>

[]
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.20.0
 - bruteforcesettings: 2.8.0
 - circles: 28.0.0-dev
 - cloud_federation_api: 1.11.0
 - comments: 1.18.0
 - contactsinteraction: 1.9.0
 - dashboard: 7.8.0
 - dav: 1.29.1
 - federatedfilesharing: 1.18.0
 - federation: 1.18.0
 - files: 2.0.0
 - files_pdfviewer: 2.9.0
 - files_reminders: 1.1.0
 - files_sharing: 1.20.0
 - files_trashbin: 1.18.0
 - files_versions: 1.21.0
 - firstrunwizard: 2.17.0
 - logreader: 2.13.0
 - lookup_server_connector: 1.16.0
 - memories: 6.1.5
 - nextcloud_announcements: 1.17.0
 - notifications: 2.16.0
 - oauth2: 1.16.3
 - onlyoffice: 9.0.0
 - password_policy: 1.18.0
 - photos: 2.4.0
 - previewgenerator: 5.4.0
 - privacy: 1.12.0
 - provisioning_api: 1.18.0
 - recommendations: 2.0.0
 - related_resources: 1.3.0
 - serverinfo: 1.18.0
 - settings: 1.10.1
 - sharebymail: 1.18.0
 - sociallogin: 5.6.1
 - support: 1.11.0
 - survey_client: 1.16.0
 - systemtags: 1.18.0
 - text: 3.9.1
 - theming: 2.3.0
 - twofactor_backupcodes: 1.17.0
 - updatenotification: 1.18.0
 - user_status: 1.8.1
 - viewer: 2.2.0
 - weather_status: 1.8.0
 - workflowengine: 2.10.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - files_rightclick: 0.15.1
 - suspicious_login
 - twofactor_totp
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.example.com",
        "192.168.14.52"
    ],
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "28.0.1.1",
    "overwrite.cli.url": "http:\/\/nextcloud.example.com",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "sendmail",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "onlyoffice": {
        "jwt_secret": "***REMOVED SENSITIVE VALUE***",
        "jwt_header": "AuthorizationJwt"
    },
    "updater.release.channel": "stable",
    "memories.ffmpeg_path": "\/usr\/bin\/ffmpeg",
    "memories.ffprobe_path": "\/usr\/bin\/ffprobe",
    "memories.tmp_path": "\/tmp\/memories",
    "memories.nvenc": true,
    "memories.exiftool": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/exiftool-amd64-glibc",
    "enabledPreviewProviders": [
        "OC\\Preview\\Image",
        "OC\\Preview\\HEIC",
        "OC\\Preview\\TIFF",
        "OC\\Preview\\Movie",
        "OC\\Preview\\MKV",
        "OC\\Preview\\MP4",
        "OC\\Preview\\AVI"
    ],
    "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
    "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
    "memories.vod.path": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
    "memories.vod.disable": false,
    "memories.gis_type": 2,
    "memories.vod.nvenc": true,
    "memories.vod.nvenc.scale": "cuda",
    "memories.vod.nvenc.temporal_aq": true,
    "mail_smtpport": "25",
    "mail_smtpsecure": "ssl",
    "trashbin_retention_obligation": "auto,30",
    "app_install_overwrite": [
        "memories",
        "files_rightclick",
        "issuetemplate"
    ],
    "memories.vod.use_gop_size": true
}
```
</details>

**Cron Configuration:** Array
(
    [backgroundjobs_mode] => cron
    [lastcron] => 1703887202
)

**External storages:** files_external is disabled

**Encryption:** no

**User-backends:** 
 * OC\User\Database

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0

**Operating system:** Windows 11

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"W4ccNO9Ko5Ib8LpczE1S","level":0,"time":"2023-12-29T21:36:17+00:00","remoteAddr":"192.168.14.175","user":"admin","app":"dav","method":"PUT","url":"/ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json","message":"No calendar events found for status check","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":{"app":"dav","user":"admin"}}
{"reqId":"V4aLy1IN2JXImqkoJuyT","level":0,"time":"2023-12-29T21:36:38+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"dav","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/user_status?format=json","message":"No calendar events found for status check","userAgent":"Mozilla/5.0 (Windows) mirall/3.11.0stable-Win64 (build 20231211) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.1.1","data":{"app":"dav","user":"nextcloud-remz"}}
{"reqId":"jRbBVIHfB41koHOb3AHa","level":0,"time":"2023-12-29T21:36:50+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"dav","method":"PUT","url":"/ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json","message":"No calendar events found for status check","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":{"app":"dav","user":"nextcloud-remz"}}
{"reqId":"aPvLBfQwyExT0J6skdXu","level":0,"time":"2023-12-29T21:36:52+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"dav","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/user_status","message":"No calendar events found for status check","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":{"app":"dav","user":"nextcloud-remz"}}
{"reqId":"btCCSSXmTiwv5i15yewp","level":0,"time":"2023-12-29T21:36:52+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"dav","method":"PUT","url":"/ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json","message":"No calendar events found for status check","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":{"app":"dav","user":"nextcloud-remz"}}
{"reqId":"flTy8PjIBRRUjuoiqtPE","level":0,"time":"2023-12-29T21:37:38+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"dav","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/user_status?format=json","message":"No calendar events found for status check","userAgent":"Mozilla/5.0 (Windows) mirall/3.11.0stable-Win64 (build 20231211) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.1.1","data":{"app":"dav","user":"nextcloud-remz"}}
{"reqId":"bFNPMBKFclsPmLkOvRJy","level":0,"time":"2023-12-29T21:38:00+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"dav","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/user_status","message":"No calendar events found for status check","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":{"app":"dav","user":"nextcloud-remz"}}
{"reqId":"9S1oGd91BeluFpGkPZG9","level":0,"time":"2023-12-29T21:38:00+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"dav","method":"PUT","url":"/ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json","message":"No calendar events found for status check","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":{"app":"dav","user":"nextcloud-remz"}}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:00+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\DAV\\SetupChecks\\NeedsSystemAddressBookSync","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:00+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\LogReader\\SetupChecks\\LogErrors","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:00+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Notifications\\Settings\\SetupWarningOnRateLimitReached","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:00+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\BruteForceThrottler","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:00+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\CheckUserCertificates","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:00+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\DatabaseHasMissingColumns","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:00+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\DatabaseHasMissingIndices","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:00+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\DatabaseHasMissingPrimaryKeys","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:00+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\DefaultPhoneRegionSet","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:00+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\EmailTestSuccessful","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:00+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\FileLocking","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:00+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\ForwardedForHeaders","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:00+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\InternetConnectivity","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:02+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\LegacySSEKeyFormat","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:02+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\MemcacheConfigured","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:02+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\PhpDefaultCharset","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:02+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\PhpFreetypeSupport","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:02+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\PhpGetEnv","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:02+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\PhpMemoryLimit","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:02+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\PhpModules","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:02+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\PhpOutdated","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:02+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\PhpOutputBuffering","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:02+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\RandomnessSecure","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:02+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\ReadOnlyConfig","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:02+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\SupportedDatabase","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:02+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\SystemIs64bit","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"N6POdkDaODUlepkC7nIl","level":0,"time":"2023-12-29T21:38:02+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\TransactionIsolation","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":[]}
{"reqId":"eY1kCRsCAdoNX0D1ny16","level":0,"time":"2023-12-29T21:38:02+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"dav","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/user_status","message":"No calendar events found for status check","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":{"app":"dav","user":"nextcloud-remz"}}
{"reqId":"aaRLcGModf6EEvWe5S6x","level":0,"time":"2023-12-29T21:38:02+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"dav","method":"PUT","url":"/ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json","message":"No calendar events found for status check","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":{"app":"dav","user":"nextcloud-remz"}}
{"reqId":"cuc0a0SUOMC49fT9Sne6","level":0,"time":"2023-12-29T21:38:10+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"dav","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/user_status","message":"No calendar events found for status check","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":{"app":"dav","user":"nextcloud-remz"}}
{"reqId":"OdGx9YecnnoPloxwNYmG","level":0,"time":"2023-12-29T21:38:10+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"dav","method":"PUT","url":"/ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json","message":"No calendar events found for status check","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0","version":"28.0.1.1","data":{"app":"dav","user":"nextcloud-remz"}}
{"reqId":"PkMzkl2T8FjSIXxiAyEw","level":0,"time":"2023-12-29T21:38:38+00:00","remoteAddr":"192.168.14.175","user":"nextcloud-remz","app":"dav","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/user_status?format=json","message":"No calendar events found for status check","userAgent":"Mozilla/5.0 (Windows) mirall/3.11.0stable-Win64 (build 20231211) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.1.1","data":{"app":"dav","user":"nextcloud-remz"}}

```

#### Browser log
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'vault')
    at notificationBar.js:98:82
    at Generator.next (<anonymous>)
    at fulfilled (notificationBar.js:7:58)

JQMIGRATE: Migrate is installed, version 3.4.1

GET https://nextcloud.example.com/apps/logreader/js/logreader-main.mjs?v=4fe0b7e0-0 net::ERR_ABORTED 404 (Not Found)
```

**Comment by xiduis15** [comment]
exactly the same problem

**Comment by joshtrichards** [comment]
> GET https://nextcloud.example.com/apps/logreader/js/logreader-main.mjs?v=4fe0b7e0-0 net::ERR_ABORTED 404 (Not Found)

This is a configuration problem. Your environment doesn't look to be handling `.mjs` files properly. Please check the Admin Manual[1] entry on this topic or the Nextcloud Help Forum (or past issues here and in the `server` repo) 

[1] https://docs.nextcloud.com/server/latest/admin_manual/release_notes/upgrade_to_27.html#web-server-configuration
[2] https://help.nextcloud.com

**Comment by remz1337** [comment]
I confirm this was the issue. Thank you
