### ISSUE TITLE
Show URL and UID in the log

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/logreader#24]

**Comment by icewind1991** [comment]
afaik we dont log that atm, so it would need to be added in core first

**Comment by LukasReschke** [comment]
We do in most cases. See the following log entry.

```
{"reqId":"AUZyiJLxbVi8UKRvC+RL","remoteAddr":"10.211.55.2","app":"no app in context","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"theming.Icon.getTouchIcon\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/media\\\/psf\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(339): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('theming.Icon.ge...', Array, 1)\\n#1 \\\/media\\\/psf\\\/nextcloud\\\/lib\\\/private\\\/URLGenerator.php(70): OC\\\\Route\\\\Router->generate('theming.Icon.ge...', Array)\\n#2 \\\/media\\\/psf\\\/nextcloud\\\/lib\\\/private\\\/URLGenerator.php(169): OC\\\\URLGenerator->linkToRoute('theming.Icon.ge...', Array)\\n#3 \\\/media\\\/psf\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template\\\/functions.php(170): OC\\\\URLGenerator->imagePath('core', 'favicon-touch.p...')\\n#4 \\\/media\\\/psf\\\/nextcloud\\\/core\\\/templates\\\/layout.guest.php(14): image_path('', 'favicon-touch.p...')\\n#5 \\\/media\\\/psf\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(174): include('\\\/media\\\/psf\\\/next...')\\n#6 \\\/media\\\/psf\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(149): OC\\\\Template\\\\Base->load('\\\/media\\\/psf\\\/next...', NULL)\\n#7 \\\/media\\\/psf\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(228): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#8 \\\/media\\\/psf\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(250): OC_Template->fetchPage()\\n#9 \\\/media\\\/psf\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(130): OC_Template->fetchPage()\\n#10 \\\/media\\\/psf\\\/nextcloud\\\/core\\\/templates\\\/403.php(7): OC\\\\Template\\\\Base->printPage()\\n#11 {main}\",\"File\":\"\\\/media\\\/psf\\\/nextcloud\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","level":3,"time":"2016-11-21T17:47:54+00:00","method":"GET","url":"\/nextcloud\/data\/htaccesstest.txt?t=1479750473680","user":"admin","version":"11.0.0.2"}
```

**Comment by LukasReschke** [comment]
`url` and `user` is what is of interest here :). Maybe combine `method` and `url`.

**Comment by LukasReschke** [comment]
And `reqId` would also be handy :)

**Comment by icewind1991** [comment]
Clicking on a log entry now highlights all entries from that request and you can search for request Ids, urls and user ids.

I'm not sure of a clean way to show this info without adding a lot of clutter but these features should cover most use cases for those fields.

**Comment by simonspa** [comment]
Sorry for digging up this old ticket. Searching for the `reqId` works, but I would also find it handy to have this as optional column to be displayed.

**Comment by xavi-GH** [comment]
Hi, we also are interested on having the possibility to optionally select which columns to show, some projects need these logs as a proof/justify they are actually using NC (audit logs). It is important to show who (not ids) is producing gets, queries ... to NC in order to show they are actively using it. Is it possible to add an option to select which columns to show?
Many thanks
