### ISSUE TITLE
after the main is empty:

### ISSUE THREAD

**Issue by cdamken** [nextcloud/logreader#7]
In the log you can see: 

```
8. {main}
```

but in the logfile you have:

```
n#8 {main}","File":"/var/www/html/owncloud/lib/private/connector/sabre/objecttree.php","Line":159}
```

The last line ist not shown.

**Comment by icewind1991** [comment]
Can you post the full log entry for this

**Comment by cdamken** [comment]
```
{"reqId":"pKEFcqx1CuZPLztWGodF","remoteAddr":"93.202.74.205","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name desktop.ini could not be located\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(920): OC\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('desktop.ini')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(327): Sabre\\\\DAV\\\\Server->getPropertiesForPath('desktop.ini', Array, 0)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropfind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":159}","level":0,"time":"2015-10-23T13:24:44+02:00","method":"PROPFIND","url":"\/remote.php\/webdav\/desktop.ini"}
```

or

```
{"reqId":"pKEFcqx1CuZPLztWGodF","remoteAddr":"93.202.74.205","app":"webdav","message":"Exception: {"Message":"HTTP/1.1 404 File with name desktop.ini could not be located","Code":0,"Trace":"
n#0 /var/www/html/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(920): OC\Connector\Sabre\ObjectTree->getNodeForPath('desktop.ini')
n#1 /var/www/html/owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(327): Sabre\DAV\Server->getPropertiesForPath('desktop.ini', Array, 0)
n#2 [internal function]: Sabre\DAV\CorePlugin->httpPropfind(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
n#3 /var/www/html/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
n#4 /var/www/html/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(469): Sabre\Event\EventEmitter->emit('method:PROPFIND', Array)
n#5 /var/www/html/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
n#6 /var/www/html/owncloud/apps/files/appinfo/remote.php(83): Sabre\DAV\Server->exec()
n#7 /var/www/html/owncloud/remote.php(132): require_once('/var/www/html/o...')
n#8 {main}","File":"/var/www/html/owncloud/lib/private/connector/sabre/objecttree.php","Line":159}","level":0,"time":"2015-10-23T13:24:44+02:00","method":"PROPFIND","url":"/remote.php/webdav/desktop.ini"}
```
all the information after the main is not shown:

![log](https://cloud.githubusercontent.com/assets/7264495/10693135/b13d5736-7996-11e5-80bb-f47325f3baa3.PNG)
